services:
  db:
    image: mysql:8.0
    container_name: stadium-db
    restart: always
    environment:
      MYSQL_DATABASE: stadium_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: stadium-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: stadium-app
    ports:
      - "8080:7860"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stadium_db?serverTimezone=Africa/Cairo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATA_REDIS_HOST: cache
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
      - cache

volumes:
  mysql_data: