services:
  db:
    image: mysql:8.0
    container_name: stadium-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: stadium-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    build: .
    container_name: stadium-app
    ports:
      - "8080:7860"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?serverTimezone=Africa/Cairo
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_DATA_REDIS_HOST: cache
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE:
    depends_on:
      - db
      - cache

volumes:
  mysql_data: